services:
  web:
    image: "ghcr.io/hggh/gps-logger/web:${VERSION:-latest}"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?error}"
      POSTGRES_DB: logger
      BOOT_MODE: web
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY:?error}"
      DJANGO_ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS}"
    ports:
      - "127.0.0.1:8080:8000"
    volumes:
      - type: bind
        source: ./django-static
        target: /static
    networks:
      - logger
  db:
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?error}"
      POSTGRES_DB: logger
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - logger

networks:
  logger:

volumes:
  db-data:
