# Generated by Django 5.1.7 on 2025-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceposition',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
