# Generated by Django 5.1.7 on 2025-03-29 13:32

import django.db.models.deletion
import django_extensions.db.fields
import logger.models.device
import logger.models.device_pub
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_deviceposition_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.SlugField(default=logger.models.device.generate_slug_token, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='DevicePub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(default=logger.models.device_pub.generate_slug_token, editable=False)),
                ('valid_until', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubs', to='logger.device')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
