# Generated by Django 5.1.7 on 2025-03-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_alter_device_token_devicepub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicepub',
            options={'ordering': ['device', 'valid_until']},
        ),
    ]
